 <script>
  $(function() {
    $( "#tabs" ).tabs();
  });
  </script>
<script type="text/javascript" src="<?php echo $this->baseUrl() . "/js/jquery/"?>messages.es.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() . "/js/jquery/"?>parsley.js"></script>
<?php
	$this->title = $this->catalog_name;//"{$this->action} {$this->catalog}";
	$this->headTitle($this->title);
?>
	 <div class='box_form'>	
		<div class='row-fluid'>
		    <div class='span7'>
		    	<h3><?php echo $this->title; ?></h3>
			</div>
	    </div>
	    <hr>
	    <div class="divisor"></div>
	  		<div id="tabs">
	  		<?php 
	  			if (is_array($this->tabs) && !empty($this->tabs)){
	  		?>		 
	  				<ul>
	  		<?php 		
	  				foreach ($this->tabs as $href => $title_tab){
	  					echo "<li><a href='#{$href}'>{$title_tab}</a></li>";
	  				}
	  			}
	  		?>       
	  				</ul>
	    	   
	    	<?php  
	    		
	    		if (!is_null($this->no_form)){
	    			echo $this->no_form;
	    		}else{
	    			//echo "<div id='tabs'>";
	    			echo $this->form;
	    			//echo "</div>";
	    		}
	    	?>
			
			
			<!-- Leyenda al final de la forma -->
			<?php 
			if (is_null($this->no_form)){
			?>
				Los campos con * son obligatorios	
			<?php 
			}		
			?>		
		</div>			
	 </div>		
	 <script type="text/javascript">
		$('#frmepidemiologia').parsley( {
			showErrors: false
		} );
	</script> 
	
	