<div class='row-fluid'>
	<div class="span4 well">
	      	<?php echo $this->form ; ?>
	      <div class='row-fluid'>
	      	 <div class="span6"><img src="<?php echo $this->baseUrl()?>/img/e1.png"/> Pacientes en consulta </div>
			 <div class="span3 text-info"><?php echo $this->estatus_consulta;?></div>
		  </div>	
		  <div class='row-fluid'> 
			 <div class="span6"><img src="<?php echo $this->baseUrl()?>/img/e2.png"/> Pacientes en espera</div>
			 <div class="span3 text-info"><?php echo $this->estatus_espera;?></div>
		  </div>
		  <div class='row-fluid'>	 
			 <div class="span6"><img src="<?php echo $this->baseUrl()?>/img/e3.png"/> Pacientes atendidos </div>
			 <div class="span3 text-info"><?php echo $this->estatus_atendido;?></div>
	      </div>	
	</div>
	<div class="span8">
	    <?php echo $this->list; ?>
	</div>	
</div>