<div class="tabbable"> <!-- Only required for left/right tabs -->
	<ul class="nav nav-tabs">
    	<li class="active"><a href="#tab1" data-toggle="tab">Ficha de identificación</a></li>
    	<li><a href="#tab2" data-toggle="tab">Perfil</a></li>
    	<li><a href="#tab3" data-toggle="tab">Motivo</a></li>
    	<li><a href="#tab4" data-toggle="tab">Padecimiento Actual</a></li>
    	<li><a href="#tab5" data-toggle="tab">Antecedentes</a></li>
    	<li><a href="#tab6" data-toggle="tab">Exploración física</a></li>
    	<li><a href="#tab7" data-toggle="tab">Extras</a></li>
    </ul>
    <div class="tab-content">
    	<div class="tab-pane active" id="tab1">
    		<?php echo $this->form;?>
    	</div>
    	<div class="tab-pane" id="tab2">
    		<p>Howdy, I'm in Section 2.</p>
    	</div>
    	<div class="tab-pane" id="tab3">
    		<p>Howdy, I'm in Section 3.</p>
    	</div>
    	<div class="tab-pane" id="tab4">
    		<p>Howdy, I'm in Section 4.</p>
    	</div>
    	<div class="tab-pane" id="tab5">
    		<p>Howdy, I'm in Section 5.</p>
    	</div>
    	<div class="tab-pane" id="tab6">
    		<p>Howdy, I'm in Section 6.</p>
    	</div>
    	<div class="tab-pane" id="tab7">
    		<p>Howdy, I'm in Section 7.</p>
    	</div>
    </div>
</div>