<div class='row-fluid well'>
	<div class='span2 offset2'>
	</div>
	<div class='row-fluid span2'>
		<div class="btn btn-large btn-primary">
			<a href='<?php echo $this->baseUrl();?>/pacientes/index/add/hc/1'>
				<span class='box_link'>Nuevo Paciente</span>
			</a>
		</div>
	</div>
	<div class='row-fluid span2'>
		<div class="btn btn-large btn-primary">
			<a href='<?php echo $this->baseUrl();?>/historialClinico/index/add'>
				<span class='box_link'>Paciente existente</span>
			</a>
		</div>
	</div>
</div>