<?php
echo $this->doctype('HTML5');
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Blue-Care');

?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
	<head>
		<?php echo $this->headMeta(); ?>
	    <meta name="description" content="">
	    <meta name="author" content="scumbagblues">
		<?php echo $this->headTitle(); ?>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?php echo $this->jQuery();?>
		<?php echo $this->headScript()->prependFile($this->baseUrl() . "/js/bootbox.js")
									   ->prependFile($this->baseUrl() . "/js/funciones.js")
									   ->prependFile($this->baseUrl() . "/js/bootstrap/bootstrap.js");?>
		<script type="text/javascript">
			bluecare.base_url = '<?php echo  $this->baseUrl()?>';
		</script>							   
		<link type="text/css" rel="stylesheet"
			href="<?php echo $this->baseUrl() . '/css/bootstrap.min.css'?>" />
		<link type="text/css" rel="stylesheet"
			href="<?php echo $this->baseUrl() . '/css/bootstrap-responsive.min.css'?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo  $this->baseUrl().'/css/jquery-ui.css'?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo  $this->baseUrl().'/css/index.css'?>" />
		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	    <!--[if lt IE 9]>
	      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	    <![endif]-->
	</head>
	<body>
	<div class="container-fluid">
		<div class="masthead">
	        <h3 class="muted"><img src="<?php echo $this->baseUrl() ?>/img/logo.png" /></h3>
	        <div class="navbar">
	          <div class="navbar-inner">
	            <div class="container">
	              <?php echo $this->menuPrincipal();?>
	            </div>
	          </div>
	        </div><!-- /.navbar -->
      	</div>
	    <div>
	      	<?php echo $this->layout()->content; ?>
	    </div>
	    <hr>
	<footer>
	   <p>Todos los derechos reservados por General DataComm de México.</p>
	</footer>
	</div> <!-- /container -->
	
	
   </body>
 </html>  