<?php
	$this->title = $this->catalog_name;//"{$this->action} {$this->catalog}";
	$this->headTitle($this->title);
?>
	 <div class='box_form'>	
		<div class='row-fluid'>
		    <div class='span4'>
		    	<h3><?php echo $this->title; ?></h3>
			</div>
	    </div>
	    <hr>
	    <div class="divisor"></div>
			<?php echo $this->form ; ?>
			<!-- Leyenda al final de la forma -->
			<?php echo $this->legend;?>
	 </div>		